### ISSUE TITLE
[Docker] Generated port is incorrrect

### ISSUE THREAD

**Issue by yeikel** [andypetrella/spark-notebook#978]
According to the [generated build](http://spark-notebook.io/dl/docker/0.7.0/2.11/2.1.1/2.7.2/true/true)

The commands to launch are the following : 

```
docker pull andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.7.2-with-hive
docker run -p 9001:9001 andypetrella/spark-notebook:0.7.0-scala-2.11.8-spark-2.1.1-hadoop-2.7.2-with-hive
```
Using that image (and I think it is the default) the port that it binds to is 9000 instead of 9001

![image](https://user-images.githubusercontent.com/8935151/50671111-d76c6c80-0f9d-11e9-883c-fd328ba85902.png)

docker-compose file that works : 

```
version: "3"
services:
    spark-notebook:
        ports:
            - '9000:9000'
        image: 'andypetrella/spark-notebook:0.8.3-scala-2.11.8-spark-2.2.2-hadoop-2.6.0-with-hive'
```

If we use the recommended ports (`9001`) it won't work
